import type { Metadata } from "next"
<<<<<<< HEAD
import { Inter, Nanum_Gothic } from "next/font/google"
import "./globals.css"
import Nav from "./ui/Nav"

const inter = Inter({ subsets: ["latin"] })
const nanum_gothic = Nanum_Gothic({
  subsets: ["latin"],
  weight: ["400", "700"],
})

export const metadata: Metadata = {
  title: "Nxstagram",
  description:
    "Nxstagram for those who want to share their thoughts or daily life.",
=======
import { Inter } from "next/font/google"
import "./globals.css"
import Navbar from "@/app/components/Navbar"
import { auth } from "@/auth"
import SwrContext from "./context/SwrContext"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 44b71e11051eb85b9d5fb50b9684715a9a08b560
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await auth()
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={nanum_gothic.className}>
        <Nav />
        {children}
=======
      <body className={inter.className}>
        <header>
          <Navbar session={session} />
        </header>
        <main className="w-full flex justify-center bgneutral-50 min-h-full">
          <SwrContext>{children}</SwrContext>
        </main>
>>>>>>> 44b71e11051eb85b9d5fb50b9684715a9a08b560
      </body>
    </html>
  )
}
