import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Navbar from "@/app/components/Navbar"
import { auth } from "@/auth"
import SwrContext from "./context/SwrContext"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await auth()
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Navbar session={session} />
        </header>
        <main className="w-full flex justify-center bgneutral-50 min-h-full">
          <SwrContext>{children}</SwrContext>
        </main>
      </body>
    </html>
  )
}
